# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20170406_1836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('name', 'parent')]),
        ),
    ]
