# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('fqdn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NodeIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='ipaddrs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.NodeIP'),
        ),
    ]
