# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddr', macaddress.fields.MACAddressField(integer=False, max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='macs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.NodeMAC'),
        ),
        migrations.AddField(
            model_name='node',
            name='nodetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.NodeType'),
        ),
    ]
