# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20170330_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeip',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipaddrs', to='nodes.Node'),
        ),
        migrations.AlterField(
            model_name='nodemac',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macaddrs', to='nodes.Node'),
        ),
    ]
