# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_auto_20170406_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesite',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unspecified/All'), (1, 'Billing'), (2, 'Physical'), (3, 'Reporting')], default=0),
        ),
        migrations.DeleteModel(
            name='NodeSitePurpose',
        ),
    ]
