# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('nodes', '0008_auto_20170406_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='default_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_site', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='nodesite',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Billing'), (2, 'Physical'), (3, 'Reporting')]),
        ),
    ]
