# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_auto_20170406_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesite',
            name='purpose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'billing'), (2, 'physical'), (3, 'reporting')]),
        ),
    ]
